require('webpack-hot-middleware/client?reload=true');
import "./styles/main.sass";
import "./views/index.pug";
import "./scripts/mainApp";
// import "./scripts/myThree2";
// import "./scripts/fireworks";
// import "./scripts/ship";
import "./scripts/theNestThree";
// import "./scripts/ballistics";
// import './scripts/spring';
// import "./scripts/myThreeSandbox";